#pragma once

#define MUTEALERT_VERSION_MAJOR 0
#define MUTEALERT_VERSION_MINOR 9
#define MUTEALERT_VERSION_PATCH 4
#define MUTEALERT_VERSION_BUILD 0

#define MUTEALERT_VERSION_STRING "0.9.4"
#define MUTEALERT_FILE_VERSION_STRING "0.9.4.0"
#define MUTEALERT_VERSION_WSTRING L"0.9.4"
